// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TourManager.DAL;

namespace TourManager.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20211217195724_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TourManager.Models.BangGia", b =>
                {
                    b.Property<int>("MaGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("GiaTour")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("MaTour")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tgbd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tgkt")
                        .HasColumnType("datetime2");

                    b.HasKey("MaGia");

                    b.HasIndex("MaTour");

                    b.ToTable("BangGias");

                    b.HasData(
                        new
                        {
                            MaGia = 1,
                            GiaTour = 3000000m,
                            MaTour = 1,
                            Tgbd = new DateTime(2021, 12, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Tgkt = new DateTime(2022, 1, 18, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            MaGia = 2,
                            GiaTour = 3500000m,
                            MaTour = 2,
                            Tgbd = new DateTime(2021, 12, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Tgkt = new DateTime(2022, 2, 2, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            MaGia = 3,
                            GiaTour = 4000000m,
                            MaTour = 3,
                            Tgbd = new DateTime(2021, 12, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Tgkt = new DateTime(2022, 1, 2, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("TourManager.Models.ChiPhi", b =>
                {
                    b.Property<int>("MaCp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("GiaTien")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("MaDoan")
                        .HasColumnType("int");

                    b.Property<int>("MaLoaiCp")
                        .HasColumnType("int");

                    b.HasKey("MaCp");

                    b.HasIndex("MaDoan");

                    b.HasIndex("MaLoaiCp");

                    b.ToTable("ChiPhis");

                    b.HasData(
                        new
                        {
                            MaCp = 1,
                            GiaTien = 1000000m,
                            MaDoan = 1,
                            MaLoaiCp = 1
                        },
                        new
                        {
                            MaCp = 2,
                            GiaTien = 1000000m,
                            MaDoan = 1,
                            MaLoaiCp = 2
                        },
                        new
                        {
                            MaCp = 3,
                            GiaTien = 1000000m,
                            MaDoan = 1,
                            MaLoaiCp = 3
                        },
                        new
                        {
                            MaCp = 4,
                            GiaTien = 700000m,
                            MaDoan = 2,
                            MaLoaiCp = 1
                        },
                        new
                        {
                            MaCp = 5,
                            GiaTien = 500000m,
                            MaDoan = 2,
                            MaLoaiCp = 2
                        },
                        new
                        {
                            MaCp = 6,
                            GiaTien = 1000000m,
                            MaDoan = 2,
                            MaLoaiCp = 3
                        },
                        new
                        {
                            MaCp = 7,
                            GiaTien = 1200000m,
                            MaDoan = 3,
                            MaLoaiCp = 1
                        },
                        new
                        {
                            MaCp = 8,
                            GiaTien = 700000m,
                            MaDoan = 3,
                            MaLoaiCp = 2
                        },
                        new
                        {
                            MaCp = 9,
                            GiaTien = 50000m,
                            MaDoan = 3,
                            MaLoaiCp = 3
                        });
                });

            modelBuilder.Entity("TourManager.Models.CtDoan", b =>
                {
                    b.Property<int>("MaCtDoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaDoan")
                        .HasColumnType("int");

                    b.Property<int>("MaKhach")
                        .HasColumnType("int");

                    b.HasKey("MaCtDoan");

                    b.HasIndex("MaDoan");

                    b.HasIndex("MaKhach");

                    b.ToTable("CtDoans");

                    b.HasData(
                        new
                        {
                            MaCtDoan = 1,
                            MaDoan = 1,
                            MaKhach = 1
                        },
                        new
                        {
                            MaCtDoan = 2,
                            MaDoan = 1,
                            MaKhach = 2
                        },
                        new
                        {
                            MaCtDoan = 3,
                            MaDoan = 1,
                            MaKhach = 3
                        },
                        new
                        {
                            MaCtDoan = 4,
                            MaDoan = 1,
                            MaKhach = 4
                        },
                        new
                        {
                            MaCtDoan = 5,
                            MaDoan = 2,
                            MaKhach = 3
                        },
                        new
                        {
                            MaCtDoan = 6,
                            MaDoan = 2,
                            MaKhach = 4
                        },
                        new
                        {
                            MaCtDoan = 7,
                            MaDoan = 2,
                            MaKhach = 5
                        },
                        new
                        {
                            MaCtDoan = 8,
                            MaDoan = 2,
                            MaKhach = 6
                        },
                        new
                        {
                            MaCtDoan = 9,
                            MaDoan = 3,
                            MaKhach = 7
                        },
                        new
                        {
                            MaCtDoan = 10,
                            MaDoan = 3,
                            MaKhach = 8
                        });
                });

            modelBuilder.Entity("TourManager.Models.CtTour", b =>
                {
                    b.Property<int>("MaCtTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaDd")
                        .HasColumnType("int");

                    b.Property<int>("MaTour")
                        .HasColumnType("int");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaCtTour");

                    b.HasIndex("MaDd");

                    b.HasIndex("MaTour");

                    b.ToTable("CtTours");

                    b.HasData(
                        new
                        {
                            MaCtTour = 1,
                            MaDd = 1,
                            MaTour = 1,
                            ThuTu = 1
                        },
                        new
                        {
                            MaCtTour = 2,
                            MaDd = 2,
                            MaTour = 1,
                            ThuTu = 2
                        },
                        new
                        {
                            MaCtTour = 3,
                            MaDd = 3,
                            MaTour = 1,
                            ThuTu = 3
                        },
                        new
                        {
                            MaCtTour = 4,
                            MaDd = 4,
                            MaTour = 1,
                            ThuTu = 4
                        },
                        new
                        {
                            MaCtTour = 5,
                            MaDd = 6,
                            MaTour = 2,
                            ThuTu = 1
                        },
                        new
                        {
                            MaCtTour = 6,
                            MaDd = 5,
                            MaTour = 2,
                            ThuTu = 2
                        },
                        new
                        {
                            MaCtTour = 7,
                            MaDd = 4,
                            MaTour = 2,
                            ThuTu = 3
                        },
                        new
                        {
                            MaCtTour = 8,
                            MaDd = 3,
                            MaTour = 3,
                            ThuTu = 1
                        },
                        new
                        {
                            MaCtTour = 9,
                            MaDd = 6,
                            MaTour = 3,
                            ThuTu = 2
                        });
                });

            modelBuilder.Entity("TourManager.Models.DiaDiem", b =>
                {
                    b.Property<int>("MaDd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenDd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDd");

                    b.ToTable("DiaDiems");

                    b.HasData(
                        new
                        {
                            MaDd = 1,
                            TenDd = "Sài Gòn"
                        },
                        new
                        {
                            MaDd = 2,
                            TenDd = "Nha Trang"
                        },
                        new
                        {
                            MaDd = 3,
                            TenDd = "Đà Lạt"
                        },
                        new
                        {
                            MaDd = 4,
                            TenDd = "Phú Quốc"
                        },
                        new
                        {
                            MaDd = 5,
                            TenDd = "Miền Tây"
                        },
                        new
                        {
                            MaDd = 6,
                            TenDd = "Sapa"
                        });
                });

            modelBuilder.Entity("TourManager.Models.Doan", b =>
                {
                    b.Property<int>("MaDoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaTour")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDoan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDoan");

                    b.HasIndex("MaTour");

                    b.ToTable("Doans");

                    b.HasData(
                        new
                        {
                            MaDoan = 1,
                            MaTour = 1,
                            NgayBd = new DateTime(2021, 12, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            NgayKt = new DateTime(2021, 12, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            NoiDung = "Nội dung 1",
                            TenDoan = "Đoàn 1"
                        },
                        new
                        {
                            MaDoan = 2,
                            MaTour = 1,
                            NgayBd = new DateTime(2021, 12, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            NgayKt = new DateTime(2021, 12, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            NoiDung = "Nội dung 2",
                            TenDoan = "Đoàn 2"
                        },
                        new
                        {
                            MaDoan = 3,
                            MaTour = 1,
                            NgayBd = new DateTime(2021, 12, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            NgayKt = new DateTime(2021, 12, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            NoiDung = "Nội dung 3",
                            TenDoan = "Đoàn 3"
                        },
                        new
                        {
                            MaDoan = 4,
                            MaTour = 2,
                            NgayBd = new DateTime(2021, 12, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            NgayKt = new DateTime(2021, 12, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            NoiDung = "Nội dung 4",
                            TenDoan = "Đoàn 4"
                        },
                        new
                        {
                            MaDoan = 5,
                            MaTour = 2,
                            NgayBd = new DateTime(2021, 12, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            NgayKt = new DateTime(2021, 12, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            NoiDung = "Nội dung 5",
                            TenDoan = "Đoàn 5"
                        },
                        new
                        {
                            MaDoan = 6,
                            MaTour = 2,
                            NgayBd = new DateTime(2021, 12, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            NgayKt = new DateTime(2021, 12, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            NoiDung = "Nội dung 6",
                            TenDoan = "Đoàn 6"
                        },
                        new
                        {
                            MaDoan = 7,
                            MaTour = 3,
                            NgayBd = new DateTime(2021, 12, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            NgayKt = new DateTime(2021, 12, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            NoiDung = "Nội dung 7",
                            TenDoan = "Đoàn 7"
                        },
                        new
                        {
                            MaDoan = 8,
                            MaTour = 3,
                            NgayBd = new DateTime(2021, 12, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            NgayKt = new DateTime(2021, 12, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            NoiDung = "Nội dung 8",
                            TenDoan = "Đoàn 8"
                        });
                });

            modelBuilder.Entity("TourManager.Models.Khach", b =>
                {
                    b.Property<int>("MaKhach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cmnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuocTich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhach");

                    b.ToTable("Khachs");

                    b.HasData(
                        new
                        {
                            MaKhach = 1,
                            Cmnd = "121234567",
                            DiaChi = "Long An",
                            GioiTinh = "Nữ",
                            QuocTich = "Vietnam",
                            Sdt = "0123456789",
                            Ten = "Nguyễn Văn Tèo"
                        },
                        new
                        {
                            MaKhach = 2,
                            Cmnd = "121234566",
                            DiaChi = "Kiên Giang",
                            GioiTinh = "Nam",
                            QuocTich = "Vietnam",
                            Sdt = "0123456788",
                            Ten = "Văn Tèo"
                        },
                        new
                        {
                            MaKhach = 3,
                            Cmnd = "121234565",
                            DiaChi = "Mỹ Tho",
                            GioiTinh = "Nữ",
                            QuocTich = "Vietnam",
                            Sdt = "0123456787",
                            Ten = "Nguyễn Văn"
                        },
                        new
                        {
                            MaKhach = 4,
                            Cmnd = "121234564",
                            DiaChi = "Củ Chi",
                            GioiTinh = "Nam",
                            QuocTich = "Vietnam",
                            Sdt = "0123456786",
                            Ten = "Nguyễn Tèo"
                        },
                        new
                        {
                            MaKhach = 5,
                            Cmnd = "121234563",
                            DiaChi = "Bến Tre",
                            GioiTinh = "Nữ",
                            QuocTich = "Vietnam",
                            Sdt = "0123456785",
                            Ten = "Nguyễn Tèo Văn"
                        },
                        new
                        {
                            MaKhach = 6,
                            Cmnd = "121234562",
                            DiaChi = "Long An",
                            GioiTinh = "Nữ",
                            QuocTich = "Vietnam",
                            Sdt = "0123456784",
                            Ten = "Trần Thị Cúc"
                        },
                        new
                        {
                            MaKhach = 7,
                            Cmnd = "121234561",
                            DiaChi = "Kiên Giang",
                            GioiTinh = "Nam",
                            QuocTich = "Vietnam",
                            Sdt = "0123456783",
                            Ten = "Thị Cúc"
                        },
                        new
                        {
                            MaKhach = 8,
                            Cmnd = "121234560",
                            DiaChi = "Bến Tre",
                            GioiTinh = "Nữ",
                            QuocTich = "Vietnam",
                            Sdt = "0123456782",
                            Ten = "Trần Cúc"
                        },
                        new
                        {
                            MaKhach = 9,
                            Cmnd = "121234559",
                            DiaChi = "Củ Chi",
                            GioiTinh = "Nam",
                            QuocTich = "Vietnam",
                            Sdt = "0123456781",
                            Ten = "Trần Thị"
                        },
                        new
                        {
                            MaKhach = 10,
                            Cmnd = "121234558",
                            DiaChi = "Mỹ Tho",
                            GioiTinh = "Nữ",
                            QuocTich = "Vietnam",
                            Sdt = "0123456780",
                            Ten = "Trần Cúc Thị"
                        });
                });

            modelBuilder.Entity("TourManager.Models.LoaiCp", b =>
                {
                    b.Property<int>("MaLoaiCp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLoaiCp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoaiCp");

                    b.ToTable("LoaiCps");

                    b.HasData(
                        new
                        {
                            MaLoaiCp = 1,
                            TenLoaiCp = "Chi phí ăn uống"
                        },
                        new
                        {
                            MaLoaiCp = 2,
                            TenLoaiCp = "Chi phí phương tiện"
                        },
                        new
                        {
                            MaLoaiCp = 3,
                            TenLoaiCp = "Chi phí khác"
                        });
                });

            modelBuilder.Entity("TourManager.Models.LoaiTour", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiTours");

                    b.HasData(
                        new
                        {
                            MaLoai = 1,
                            TenLoai = "Du lịch di động"
                        },
                        new
                        {
                            MaLoai = 2,
                            TenLoai = "Du lịch kết hợp nghề nghiệp"
                        },
                        new
                        {
                            MaLoai = 3,
                            TenLoai = "Du lịch xã hội và gia đình"
                        },
                        new
                        {
                            MaLoai = 4,
                            TenLoai = "Du lịch ẩm thực"
                        });
                });

            modelBuilder.Entity("TourManager.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNv");

                    b.ToTable("NhanViens");

                    b.HasData(
                        new
                        {
                            MaNv = 1,
                            GioiTinh = "Nam",
                            Sdt = "0198765432",
                            TenNv = "Lê Văn Tèo"
                        },
                        new
                        {
                            MaNv = 2,
                            GioiTinh = "Nữ",
                            Sdt = "0198765433",
                            TenNv = "Lê Tèo Văn"
                        },
                        new
                        {
                            MaNv = 3,
                            GioiTinh = "Nam",
                            Sdt = "0198765434",
                            TenNv = "Văn Lê Tèo"
                        },
                        new
                        {
                            MaNv = 4,
                            GioiTinh = "Nữ",
                            Sdt = "0198765435",
                            TenNv = "Tèo Lê Văn"
                        },
                        new
                        {
                            MaNv = 5,
                            GioiTinh = "Nam",
                            Sdt = "0198765436",
                            TenNv = "Trần Văn A"
                        },
                        new
                        {
                            MaNv = 6,
                            GioiTinh = "Nữ",
                            Sdt = "0198765437",
                            TenNv = "A Trần Văn"
                        },
                        new
                        {
                            MaNv = 7,
                            GioiTinh = "Nam",
                            Sdt = "0198765438",
                            TenNv = "Trần A Văn"
                        });
                });

            modelBuilder.Entity("TourManager.Models.PhanCong", b =>
                {
                    b.Property<int>("MaPhanCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaDoan")
                        .HasColumnType("int");

                    b.Property<int>("MaNv")
                        .HasColumnType("int");

                    b.Property<string>("NhiemVu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhanCong");

                    b.HasIndex("MaDoan");

                    b.HasIndex("MaNv");

                    b.ToTable("PhanCongs");

                    b.HasData(
                        new
                        {
                            MaPhanCong = 1,
                            MaDoan = 1,
                            MaNv = 1,
                            NhiemVu = "Lái xe"
                        },
                        new
                        {
                            MaPhanCong = 2,
                            MaDoan = 1,
                            MaNv = 2,
                            NhiemVu = "Hướng dẫn viên"
                        },
                        new
                        {
                            MaPhanCong = 3,
                            MaDoan = 1,
                            MaNv = 3,
                            NhiemVu = "Thông dịch viên"
                        },
                        new
                        {
                            MaPhanCong = 4,
                            MaDoan = 1,
                            MaNv = 4,
                            NhiemVu = "Phục vụ"
                        },
                        new
                        {
                            MaPhanCong = 5,
                            MaDoan = 2,
                            MaNv = 5,
                            NhiemVu = "Lái xe"
                        },
                        new
                        {
                            MaPhanCong = 6,
                            MaDoan = 2,
                            MaNv = 6,
                            NhiemVu = "Hướng dẫn viên"
                        },
                        new
                        {
                            MaPhanCong = 7,
                            MaDoan = 3,
                            MaNv = 3,
                            NhiemVu = "Lái xe"
                        },
                        new
                        {
                            MaPhanCong = 8,
                            MaDoan = 3,
                            MaNv = 4,
                            NhiemVu = "Phục vụ"
                        });
                });

            modelBuilder.Entity("TourManager.Models.Tour", b =>
                {
                    b.Property<int>("MaTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DacDiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("TenTour")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTour");

                    b.HasIndex("MaLoai");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            MaTour = 1,
                            DacDiem = "Đặc điểm tour 1",
                            MaLoai = 4,
                            TenTour = "Tour 1"
                        },
                        new
                        {
                            MaTour = 2,
                            MaLoai = 3,
                            TenTour = "Tour 2"
                        },
                        new
                        {
                            MaTour = 3,
                            DacDiem = "Đặc điểm tour 3",
                            MaLoai = 2,
                            TenTour = "Tour 3"
                        });
                });

            modelBuilder.Entity("TourManager.Models.BangGia", b =>
                {
                    b.HasOne("TourManager.Models.Tour", "Tour")
                        .WithMany("BangGias")
                        .HasForeignKey("MaTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TourManager.Models.ChiPhi", b =>
                {
                    b.HasOne("TourManager.Models.Doan", "Doan")
                        .WithMany("ChiPhis")
                        .HasForeignKey("MaDoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourManager.Models.LoaiCp", "LoaiCp")
                        .WithMany("ChiPhis")
                        .HasForeignKey("MaLoaiCp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doan");

                    b.Navigation("LoaiCp");
                });

            modelBuilder.Entity("TourManager.Models.CtDoan", b =>
                {
                    b.HasOne("TourManager.Models.Doan", "Doan")
                        .WithMany("CtDoans")
                        .HasForeignKey("MaDoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourManager.Models.Khach", "Khach")
                        .WithMany("CtDoans")
                        .HasForeignKey("MaKhach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doan");

                    b.Navigation("Khach");
                });

            modelBuilder.Entity("TourManager.Models.CtTour", b =>
                {
                    b.HasOne("TourManager.Models.DiaDiem", "DiaDiem")
                        .WithMany("CtTours")
                        .HasForeignKey("MaDd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourManager.Models.Tour", "Tour")
                        .WithMany("CtTours")
                        .HasForeignKey("MaTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaDiem");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TourManager.Models.Doan", b =>
                {
                    b.HasOne("TourManager.Models.Tour", "Tour")
                        .WithMany("Doans")
                        .HasForeignKey("MaTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TourManager.Models.PhanCong", b =>
                {
                    b.HasOne("TourManager.Models.Doan", "Doan")
                        .WithMany("PhanCongs")
                        .HasForeignKey("MaDoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TourManager.Models.NhanVien", "NhanVien")
                        .WithMany("PhanCongs")
                        .HasForeignKey("MaNv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doan");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("TourManager.Models.Tour", b =>
                {
                    b.HasOne("TourManager.Models.LoaiTour", "LoaiTour")
                        .WithMany("Tours")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiTour");
                });

            modelBuilder.Entity("TourManager.Models.DiaDiem", b =>
                {
                    b.Navigation("CtTours");
                });

            modelBuilder.Entity("TourManager.Models.Doan", b =>
                {
                    b.Navigation("ChiPhis");

                    b.Navigation("CtDoans");

                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("TourManager.Models.Khach", b =>
                {
                    b.Navigation("CtDoans");
                });

            modelBuilder.Entity("TourManager.Models.LoaiCp", b =>
                {
                    b.Navigation("ChiPhis");
                });

            modelBuilder.Entity("TourManager.Models.LoaiTour", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("TourManager.Models.NhanVien", b =>
                {
                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("TourManager.Models.Tour", b =>
                {
                    b.Navigation("BangGias");

                    b.Navigation("CtTours");

                    b.Navigation("Doans");
                });
#pragma warning restore 612, 618
        }
    }
}
